### PR TITLE
Add game notes support

### PR DESCRIPTION
**Pull request by davwheat**
Today I added [support for game notes to the API](https://github.com/davwheat/world-cup-of-tocs-api/blob/6fa2f1c2b3741e595ff0ba43d1d9174052c68303/game-notes.json). This allows us to add notes to specific game if there's an issue with the data, or to answer any FAQs we get.

This PR adds front-end support for these notes.

---

A small link (`<button>`) shows under any games which have notes set for them on the API:

image

Clicking this link opens a modal which displays the notes as bullet points:

image

This modal can be closed by clicking the close button at the top right, pressing Escape, or clicking the backdrop.

On mobile, the modal fills the entire viewport, just showing the close button as a method of exiting:

image

### CODE REVIEW

**Comment by Gum-Joe** [comment]
Wow, this is brilliant! Also very nice PR. Will have a full review either later tonight or more likely tommorow.

Whilst we're hear coild we add "news" headline, similar to how we had the red quotes on the tube world cup site? (maybe reuse the old "graphs are out of proportion" stuff?)

Image from the tube world cup site ( said e.g. "BREAKING: crowds have gathered at St Pancreas to witness this closely contested match" during the cup):

**Comment by Gum-Joe** [comment]
@davwheat Will the above be added, and if not, is this PR then ready for reviw?

**Comment by davwheat** [comment]
Never got an email for your comment! 😆

Yeah, we can do that news headline. I don't want it to be in red though. 😛

Another API endpoint, or should be fetch direct from a JSON on GitHub for if we can't update the API because I'm oversleeping again.

**Comment by Gum-Joe** [comment]
> Never got an email for your comment! 😆
> 
> Yeah, we can do that news headline. I don't want it to be in red though. 😛
> 
> Another API endpoint, or should be fetch direct from a JSON on GitHub for if we can't update the API because I'm oversleeping again.

Ok - I would say do another API endpoint, especially since I think we should move to a cloud based API so that we can have CI (see davwheat/world-cup-of-tocs-api#7)

**Comment by davwheat** [comment]
It's just a lot of work to move it to cloud infrastructure, especially since things like this have to use something like Google Cloud Run, which can become expensive, especially since our egress will slowly get higher with all the poll data.

Our egress will probably become about 5-20 GB/mth.

Turns out it's only about $2/mth but still... :P

image

**Comment by Gum-Joe** [comment]
1. We create a new googel account
2. We get $200 credit
3. use the credit.
I mean this server only runs for 1 month, so even at $5 a month for two month we use... $10 of credit. From $200.

**Comment by davwheat** [comment]
> BTW why on "us-east1 or us-central1, not London"?

Free tier only applies at these locations (otherwise we'd be charged for all the vCPU-seconds, etc.

**Comment by Gum-Joe** [comment]
> > BTW why on "us-east1 or us-central1, not London"?
> 
> Free tier only applies at these locations (otherwise we'd be charged for all the vCPU-seconds, etc.

Ahhhh, you've got them confused,

There's a free tier which yes, only runs in those locations.
l'm talking about the free trial credit, which can be used anywhere.

(just checked, I have a g1-small instance in europe-west-b I haven't paid a penny for it - all from the free credit)

**Review by Gum-Joe — DISMISSED** [review]
APPROVED!

Looks brilliant. Just some code documentation issues, but nothing I'd consider blocking (up to you if you want to make them prior to merging).

Have looked at site and made some minor style changes, but everything looks good, including on mobile.

**Pull request merged**
